apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-service
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
    app: {{ .Values.label.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
    app: {{ .Values.label.app }}
